= XFCE Night Mode

Shell script that allows you to easily *switch between dark and light variants
of a theme*. When used as a
https://docs.xfce.org/panel-plugins/xfce4-genmon-plugin[Generic Monitor
(Genmon)] plugin, it will automatically switch at the times specified.

video::https://i.imgur.com/hnPtVPr.mp4[width=400]

It is *important that both the color scheme and the icon theme have both light
and dark variants*. For example, the Adwaita and Adwaita-dark GTK style and
the Elementary and Elementary-dark icon theme are such.

* https://gitlab.com/bimlas/xfce4-night-mode (main repository)
* https://github.com/bimlas/xfce4-night-mode (mirror, *please star if you like the plugin*)

== Command line usage

....
$ xfce4-night-mode.sh [day|night|toggle]
....

*Parameters*

`day`:: Use light variant
`night`:: Use dark variant
`toggle`:: Switch between light and dark variants

Without parameters, it will use dark variant from sunset to sunrise according
to the settings (see later).

== Generic Monitor (Genmon) plugin usage

* First you have to install `xfce4-genmon-plugin` package if it is not on your system
* Add the monitor to the panel
** Right click on the panel
** Select _Panel -> Add new items_
** Add _Generic Monitor_ plugin
* Set up the generic monitor to use with night mode
** Right click on the newly added generic monitor -> _Properties_
** Command: `/path/to/xfce4-night-mode.sh`
** Uncheck the checkbox of _Label_
** Set _Period_ to `300` seconds (5 minutes)

== Settings

For settings, open the XFCE Settings Editor -> `night-mode` channel.
